default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: todo_app
  password: admin001
  socket: /tmp/mysql.sock

development:
  <<: *default
  database: todo_app_development

test:
  <<: *default
  database: todo_app_test

#production:
#  <<: *default
#  database: todo_app_production
#  username: todo_app
#  password: admin001
