inherit_gem:
  fablicop:
    - "config/.base_rubocop.yml"

AllCops:
  Exclude:
    - 'Gemfile'
    - 'Rakefile'
    - 'config.ru'
    - 'bin/**/*'
    - 'node_modules/**/*'
    - 'config/**/*'
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'spec/rails_helper.rb'
    - 'spec/spec_helper.rb'

Style/FrozenStringLiteralComment:
  Exclude:
    - 'app/channels/**/*'
    - 'app/jobs/**/*'
    - 'app/mailers/**/*'
    - 'app/models/application_record.rb'
    - 'db/migrate/*'
    - 'spec/support/selenium_chrome.rb'
