development:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: training
  pool: 5
  username: training-develop
  password: test1234
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: training_test
  pool: 5
  username: training-test
  password: test5555
  host: localhost
