inherit_gem:
  fablicop:
    - "config/.base_rubocop.yml"

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - bin/**/*
    - config/**/*
    - node_modules/**/*
    - db/**/*
    - test/**/*
    - config.ru
    - Rakefile
    - Gemfile
