inherit_gem:
  fablicop:

AllCops:
  TargetRubyVersion: 2.5
  Exclude:
    - bin/**/*
    - config/**/*
    - node_modules/**/*
    - db/**/*
    - test/**/*
    - config.ru
    - Rakefile
    - Gemfile

AsciiComments:
  Enabled: false

Metrics/BlockLength:
  Exclude:
    - 'spec/**/*'
