version: "3"
services:
  db:
    image: "mysql:5.6.51"
    container_name: yaraneba-db
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: yaraneba_development
      MYSQL_USER: yoikawa
      MYSQL_PASSWORD: yoikawa
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  db-test:
    image: "mysql:5.6.51"
    container_name: yaraneba-db-test
    ports:
      - "3316:3316"
    environment:
      MYSQL_ROOT_PASSWORD: 12345678
      MYSQL_DATABASE: yaraneba_test
      MYSQL_USER: yoikawa
      MYSQL_PASSWORD: yoikawa
      TZ: 'Asia/Tokyo'
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci
  web:
    build:
      context: ../
      dockerfile: ./docker/Dockerfile
    container_name: yaraneba
    links:
      - db
      - db-test
    tty: true
    ports:
      - "3000:3000"
    environment:
      - "SELENIUM_DRIVER_URL=http://selenium_chrome:4444/wd/hub"
  selenium_chrome:
    image: selenium/standalone-chrome-debug
    ports:
      - 4444:4444
