version: '3'

services:
  mysql:
    image: mysql:8
    environment:
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"
      MYSQL_DATABASE: todo_app
      MYSQL_ROOT_PASSWORD: ""
      TZ: Asia/Tokyo
    ports:
      - "3307:3306"
    volumes:
      - ./mysql/conf.d:/etc/mysql/conf.d
      - ./mysql/initdb.d:/docker-entrypoint-initdb.d
      # Data Volume
      - mysql-data:/var/lib/mysql

volumes:
  mysql-data:
