inherit_gem:
  fablicop:
    - "config/.base_rubocop.yml"

Style/FrozenStringLiteralComment:
  Exclude:
    - 'db/**/*'
    - 'spec/**/*'

AllCops:
  TargetRubyVersion: 2.5.7
  Exclude:
    - 'node_modules/**/*'
    - 'bin/**/*'
    - 'config/**/*'
    - 'db/schema.rb'
    - 'db/seeds.rb'
    - 'Rakefile'
    - 'config.ru'
