development:
  adapter: mysql2
  encoding: utf8
  database: taskmanager_development
  pool: 5
  username: taskmanager-user
  password: taskmanager-password
  host: localhost

test:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: taskmanager_test
  pool: 5
  username: taskmanager-user
  password: taskmanager-password
  host: localhost

production:
  adapter: mysql2
  encoding: utf8
  reconnect: false
  database: taskmanager_development
  pool: 5
  username: taskmanager-user
  password: taskmanager-password
  host: localhost
