default: &default
  adapter: mysql2
  encoding: utf8
  pool: 5
  username: root
  host: localhost

development:
  <<: *default
  database: tms_development
  
test:
  <<: *default
  database: tms_test

production:
  <<: *default
  database: tms_production

