mysql: &mysql
  adapter: mysql2
  host: 127.0.0.1
  username: root
  password:
  database: guild
  encoding: utf8mb4

development:
  <<: *mysql

local:
  <<: *mysql

test:
  <<: *mysql

production:
  <<: *mysql
