mysql: &mysql
  adapter: mysql2
  host: 127.0.0.1
  username: root
  password:
  database: guild_<%= Rails.env %>
  encoding: utf8mb4

development:
  <<: *mysql
  database: guild

local:
  <<: *mysql
  database: guild

test:
  <<: *mysql

production:
  <<: *mysql
