default: &default
  adapter: mysql2
  encoding: utf8mb4
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>
  username: root
  password: 'passwords'
  host: db

development:
  <<: *default
  database: job_san_development

test:
  <<: *default
  database: job_san_test

production:
  <<: *default
  database: job_san_production
  username: job_san
  password: <%= ENV['JOB_SAN_DATABASE_PASSWORD'] %>
