version: '3.1'

services:
  db:
    image: mysql:5.6
    restart: always
    hostname: my-mysql
    env_file:
      - .env
    environment:
      MYSQL_USER: my_user
      TZ: Japan
    ports:
      - 3306:3306
    tty: true
