services:
  db:
    image: "mysql:8.0.18"
    ports:
      - "3306:3306"
    volumes:
      - ./docker/app/db/my.cnf:/etc/mysql/conf.d/my.cnf
    environment:
      MYSQL_DATABASE: job_san_development
      MYSQL_ROOT_PASSWORD: "password"
  web:
    build: .
    volumes:
      - .:/usr/src/app
      - vendor_bundle:/user/src/app/vendor/bundle
    ports:
      - "3000:3000"
    depends_on:
      - db
    command: rails s -b 0.0.0.0

volumes:
  vendor_bundle:
    driver: local
