version: '3'
services:
  db:
    image: mysql:5.7
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    volumes:
      - db-data:/var/lib/mysql
    command: mysqld --character-set-server=utf8mb4 --collation-server=utf8mb4_unicode_ci

  api:
    build: .
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    ports:
      - "3002:3000"
    environment:
      RAILS_ENV: production
      RAILS_SERVE_STATIC_FILES: 'true'
    depends_on:
      - db

volumes:
  db-data:
    driver: local
