name: CI

on: [pull_request]

jobs:
  myapp-test:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: myapp
    steps:
      - uses: actions/checkout@v2
      - run: docker-compose up -d --build
      - run: docker-compose exec api bundle exec rails webpacker:compile
      - run: docker-compose exec api bundle exec rspec
