name: Rubocop
on: push

jobs:
  rubocop:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2

      - name: Set up Ruby
        uses: ruby/setup-ruby@v1
        with:
          ruby-version: 3.0.1

      - name: Install dependent libralies
        run: sudo apt-get install libmysqlclient-dev
        working-directory: todo_app

      - name: Setup bundler
        run: gem install bundler
        working-directory: todo_app

      - name: bundle install
        run: |
          bundle install --jobs 4 --retry 3
        working-directory: todo_app

      - name: Rubocop checks
        run: bundle exec rubocop
        working-directory: todo_app
