apiVersion: v1
kind: ReplicationController
metadata:
  name: rails
spec:
  replicas: 3
  selector:
    app: rails
  template:
    metadata:
      name: rails
      labels:
        app: rails
    spec:
      containers:
      - name: rails
        image: lastgleam/dongheetodo-rails:latest
        command: ["bundle", "exec", "rails", "s", "-p", "3000", "-b", "0.0.0.0"]
        env:
          - name: RAILS_ENV
            value: development
          - name: MYSQL_HOST
            value: mysql.default.svc.cluster.local
          - name: MYSQL_USER
            value: root
          - name: MYSQL_PASSWORD
            value: root
        ports:
        - containerPort: 3000
---
apiVersion: v1
kind: Service
metadata:
  name: rails
spec:
  ports:
  - port: 3000
    targetPort: 3000
    protocol: TCP
  type: LoadBalancer
  selector:
    app: rails
